@startuml

header Acornsoft
hide footbox
skinparam partition{
	BackgroundColor #eeeeee
	BorderColor #777777
}

title
	<u>Test Scenario #4</u>
	<font size="9">라우팅 정책 반영 소요시간</font>

end title


start

	repeat
		partition 정책확인 {
			:현재 라우팅정책 확인;
		}

		partition 정책반영 {
			if (라우팅 정책 A ?) then (Yes)
				#palegreen::정책 B 반영;
				note left
					리뷰 STAR 조회 처리
					(STAR FOUND)
				end note

				while (반영 여부 (FOUND) ?) is (No)
					:서비스 페이지 요청;
				endwhile (Yes)
			else (No)
				#palegreen::정책 A 반영;
				note right
					리뷰 STAR 조회 중지처리
					(STAR NOT_FOUND)
				end note

				while (반영 여부 (NOT_FOUND) ?) is (No)
					:서비스 페이지 요청;
				endwhile (Yes)
			endif
		}
	repeatwhile (수행회수<=1000)

stop


@enduml