@startuml

header Acornsoft
hide footbox
skinparam partition{
	BackgroundColor #eeeeee
	BorderColor #777777
}

title
	<u>Test Scenario #2</u>
	<font size="9">장애발생 분석추적 성공률</font>

end title

start

	repeat

		partition Clean {
			:장애 Clean 처리(code=**200**) ;
			note right
				* 상태코드 200 : 정상
				* 상태코드 503 : 오류
			end note

			while (Clean 여부 확인 ?\n상태코드==200) is (No)
				:서비스 페이지 호출 #1;
			endwhile (Yes)

			:메트릭 정보 Clean;
			while (분석결과 정상상태 확인 ?) is (No)
				:장애분석결과 조회;
			endwhile (Yes)

		}

		partition 장애주입 {
			:장애 주입(code=**503**);

			while (상태코드==503 ?) is (No)
				:서비스 페이지 요청(HTTP);
			endwhile (Yes)

		}

		partition 장애분석추적 {

			while (분석결과 장애상태 확인 ?) is (No)
				:장애분석결과 조회;
			endwhile (Yes)

			if (처리시간 10초이내) then (Yes)
				:성공;
			else (No)
				:실패;
			endif

		}

	repeatwhile (수행회수<=100)

stop



@enduml
